//contact input
/*
const serverFormInput = {
  contactDocumentFile: {
    toString: [Function],
    getName: [Function],
    getBytes: [Function],
    setName: [Function],
    getContentType: [Function],
    setContentType: [Function],
    getDataAsString: [Function],
    isGoogleType: [Function],
    getAllBlobs: [Function],
    setDataFromString: [Function],
    copyBlob: [Function],
    setContentTypeFromExtension: [Function],
    setBytes: [Function],
    getAs: [Function],
    contents: '',
    length: 0,
    name: '',
    type: 'application/octet-stream',
  },
  companyPhone1: '',
  contactMobile2: '',
  contactSex: 'เพศ',
  extensionNo: '',
  contactLineName: '',
  contactMobile1: '',
  contactPosition: '',
  companyName: '',
  formType: 'contact',
  contactName: 'cccccccccc',
  contactLineProfileFile: {
    toString: [Function],
    getName: [Function],
    getBytes: [Function],
    setName: [Function],
    getContentType: [Function],
    setContentType: [Function],
    getDataAsString: [Function],
    isGoogleType: [Function],
    getAllBlobs: [Function],
    setDataFromString: [Function],
    copyBlob: [Function],
    setContentTypeFromExtension: [Function],
    setBytes: [Function],
    getAs: [Function],
    contents: '',
    length: 0,
    name: '',
    type: 'application/octet-stream',
  },
  contactEmail: '',
  contactNote: 'vvvvvvvvvvv',
  contactNickName: '',
}
*/
